version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # MQTT over WebSockets port
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/pwfile:/mosquitto/config/pwfile

  logger:
    build:
      context: ./logger # Context relative to this compose file
    container_name: health_logger
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data # Maps internal /app/data to local server/data folder
    environment:
      PYTHONUNBUFFERED: 1
